"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import Navbar from "@/components/Navbar";

type HealthStatus = "Healthy" | "Warning" | "Critical";

type ModuleDefinition = {
  key: string;
  label: string;
  category:
    | "Store"
    | "Orders"
    | "Products"
    | "Delivery"
    | "Marketing"
    | "Support"
    | "Notifications"
    | "Content"
    | "Settings"
    | "Subscriptions";
  description: string;
  required: boolean;
  warnIfEmpty?: boolean;
  actionHref: string;
  actionLabel: string;
};

type HealthItem = ModuleDefinition & {
  exists: boolean;
  count: number;
  status: HealthStatus;
  message: string;
};

const moduleDefinitions: ModuleDefinition[] = [
  {
    key: "pujafresh-products",
    label: "Product Catalog",
    category: "Products",
    description: "Products must be available for customer browsing and checkout.",
    required: true,
    warnIfEmpty: true,
    actionHref: "/admin/products",
    actionLabel: "Manage Products",
  },
  {
    key: "pujafresh-orders",
    label: "Orders",
    category: "Orders",
    description: "Customer orders power admin dashboard, invoices and delivery flow.",
    required: false,
    warnIfEmpty: false,
    actionHref: "/admin",
    actionLabel: "Open Orders",
  },
  {
    key: "pujafresh-subscriptions",
    label: "Subscriptions",
    category: "Subscriptions",
    description: "Repeat delivery subscriptions, approval status, next delivery dates and frequency rules.",
    required: false,
    warnIfEmpty: false,
    actionHref: "/admin/subscriptions",
    actionLabel: "Subscriptions",
  },
  {
    key: "pujafresh-store-settings",
    label: "Store Settings",
    category: "Settings",
    description: "Store details, delivery charges, payment methods and checkout rules.",
    required: true,
    actionHref: "/admin/store-settings",
    actionLabel: "Store Settings",
  },
  {
    key: "pujafresh-delivery-areas",
    label: "Delivery Areas",
    category: "Delivery",
    description: "Serviceable pincodes are required for checkout delivery validation.",
    required: true,
    warnIfEmpty: true,
    actionHref: "/admin/delivery-areas",
    actionLabel: "Delivery Areas",
  },
  {
    key: "pujafresh-delivery-slots",
    label: "Delivery Slots",
    category: "Delivery",
    description: "Active slots are required for customers to select delivery time.",
    required: true,
    warnIfEmpty: true,
    actionHref: "/admin/delivery-slots",
    actionLabel: "Delivery Slots",
  },
  {
    key: "pujafresh-delivery-partners",
    label: "Delivery Partners",
    category: "Delivery",
    description: "Delivery partners are required for order assignment and partner portal.",
    required: true,
    warnIfEmpty: true,
    actionHref: "/admin/delivery-partners",
    actionLabel: "Delivery Partners",
  },
  {
    key: "pujafresh-delivery-feedback",
    label: "Delivery Feedback",
    category: "Delivery",
    description: "Customer delivery ratings and complaints after delivery.",
    required: false,
    actionHref: "/admin/delivery-feedback",
    actionLabel: "Delivery Feedback",
  },
  {
    key: "pujafresh-coupons",
    label: "Coupons",
    category: "Marketing",
    description: "Discount coupons and marketing offers.",
    required: false,
    actionHref: "/admin/coupons",
    actionLabel: "Manage Coupons",
  },
  {
    key: "pujafresh-coupon-usage",
    label: "Coupon Usage",
    category: "Marketing",
    description: "Coupon usage analytics and savings records.",
    required: false,
    actionHref: "/admin/coupon-usage",
    actionLabel: "Coupon Usage",
  },
  {
    key: "pujafresh-loyalty-points",
    label: "Loyalty Points",
    category: "Marketing",
    description: "Customer loyalty points earned and redeemed.",
    required: false,
    actionHref: "/admin/loyalty",
    actionLabel: "Loyalty Points",
  },
  {
    key: "pujafresh-newsletter-subscribers",
    label: "Newsletter Subscribers",
    category: "Marketing",
    description: "Newsletter customer list for marketing communication.",
    required: false,
    actionHref: "/admin/newsletter",
    actionLabel: "Newsletter",
  },
  {
    key: "pujafresh-customer-notifications",
    label: "Customer Notifications",
    category: "Notifications",
    description: "Customer alerts generated by orders, delivery, payments and broadcasts.",
    required: false,
    actionHref: "/admin/notification-logs",
    actionLabel: "Notification Logs",
  },
  {
    key: "pujafresh-support-tickets",
    label: "Support Tickets",
    category: "Support",
    description: "Customer support messages and admin replies.",
    required: false,
    actionHref: "/admin/support",
    actionLabel: "Support",
  },
  {
    key: "pujafresh-inventory-history",
    label: "Inventory History",
    category: "Products",
    description: "Stock change logs for orders, cancellations and manual updates.",
    required: false,
    actionHref: "/admin/inventory-history",
    actionLabel: "Inventory History",
  },
  {
    key: "pujafresh-faqs",
    label: "FAQs",
    category: "Content",
    description: "FAQ content for customer help center.",
    required: false,
    actionHref: "/admin/faqs",
    actionLabel: "FAQs",
  },
  {
    key: "pujafresh-announcements",
    label: "Announcements",
    category: "Content",
    description: "Website announcement bar messages and offer banners.",
    required: false,
    actionHref: "/admin/announcements",
    actionLabel: "Announcements",
  },
];

const categoryFilters = [
  "All Categories",
  "Store",
  "Orders",
  "Products",
  "Delivery",
  "Marketing",
  "Support",
  "Notifications",
  "Content",
  "Settings",
  "Subscriptions",
];

const statusFilters = ["All Status", "Healthy", "Warning", "Critical"];

const readLocalStorageValue = (key: string) => {
  try {
    const savedValue = localStorage.getItem(key);

    if (!savedValue) return null;

    try {
      return JSON.parse(savedValue);
    } catch {
      return savedValue;
    }
  } catch {
    return null;
  }
};

const getRecordCount = (value: unknown) => {
  if (Array.isArray(value)) return value.length;
  if (value && typeof value === "object") return 1;
  if (typeof value === "string" && value.trim().length > 0) return 1;

  return 0;
};

const getStatusBadgeClass = (status: HealthStatus) => {
  if (status === "Healthy") return "bg-green-50 text-green-700";
  if (status === "Warning") return "bg-orange-50 text-orange-700";

  return "bg-red-50 text-red-700";
};

const getCategoryBadgeClass = (category: string) => {
  if (category === "Delivery") return "bg-blue-50 text-blue-700";
  if (category === "Marketing") return "bg-[#fff7ed] text-[#7a1e13]";
  if (category === "Products") return "bg-purple-50 text-purple-700";
  if (category === "Support") return "bg-indigo-50 text-indigo-700";
  if (category === "Notifications") return "bg-pink-50 text-pink-700";
  if (category === "Settings") return "bg-gray-100 text-gray-700";
  if (category === "Subscriptions") return "bg-orange-50 text-orange-700";

  return "bg-green-50 text-green-700";
};

const buildHealthItem = (definition: ModuleDefinition): HealthItem => {
  const value = readLocalStorageValue(definition.key);
  const exists = value !== null;
  const count = getRecordCount(value);

  if (definition.required && !exists) {
    return {
      ...definition,
      exists,
      count,
      status: "Critical",
      message: "Required module data is missing.",
    };
  }

  if (definition.warnIfEmpty && count === 0) {
    return {
      ...definition,
      exists,
      count,
      status: "Warning",
      message: "Module exists but has no usable records.",
    };
  }

  if (!exists) {
    return {
      ...definition,
      exists,
      count,
      status: "Warning",
      message: "No data yet. This is fine if the feature has not been used.",
    };
  }

  return {
    ...definition,
    exists,
    count,
    status: "Healthy",
    message: "Module data is available.",
  };
};

export default function AdminSystemHealthPage() {
  const router = useRouter();

  const [healthItems, setHealthItems] = useState<HealthItem[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All Categories");
  const [statusFilter, setStatusFilter] = useState("All Status");
  const [isCheckingAuth, setIsCheckingAuth] = useState(true);

  useEffect(() => {
    const isAdminLoggedIn = localStorage.getItem("pujafresh-admin-auth");

    if (isAdminLoggedIn !== "true") {
      router.push("/admin/login");
      return;
    }

    runHealthCheck();
    setIsCheckingAuth(false);
  }, [router]);

  const runHealthCheck = () => {
    setHealthItems(moduleDefinitions.map(buildHealthItem));
  };

  const filteredHealthItems = useMemo(() => {
    const search = searchQuery.trim().toLowerCase();

    return healthItems.filter((item) => {
      const matchesSearch =
        search.length === 0 ||
        item.label.toLowerCase().includes(search) ||
        item.key.toLowerCase().includes(search) ||
        item.description.toLowerCase().includes(search) ||
        item.message.toLowerCase().includes(search) ||
        item.category.toLowerCase().includes(search) ||
        item.status.toLowerCase().includes(search);

      const matchesCategory =
        categoryFilter === "All Categories" || item.category === categoryFilter;

      const matchesStatus =
        statusFilter === "All Status" || item.status === statusFilter;

      return matchesSearch && matchesCategory && matchesStatus;
    });
  }, [categoryFilter, healthItems, searchQuery, statusFilter]);

  const stats = useMemo(() => {
    const healthy = healthItems.filter((item) => item.status === "Healthy").length;
    const warning = healthItems.filter((item) => item.status === "Warning").length;
    const critical = healthItems.filter((item) => item.status === "Critical").length;
    const records = healthItems.reduce((sum, item) => sum + item.count, 0);
    const score =
      healthItems.length === 0
        ? 0
        : Math.max(
            0,
            Math.round(((healthy * 100 + warning * 45) / (healthItems.length * 100)) * 100)
          );

    return {
      total: healthItems.length,
      healthy,
      warning,
      critical,
      records,
      score,
      modulesWithData: healthItems.filter((item) => item.exists).length,
    };
  }, [healthItems]);

  const clearFilters = () => {
    setSearchQuery("");
    setCategoryFilter("All Categories");
    setStatusFilter("All Status");
  };

  const exportCsv = () => {
    if (filteredHealthItems.length === 0) {
      toast.error("No health records to export");
      return;
    }

    const headers = [
      "Module",
      "Key",
      "Category",
      "Status",
      "Records",
      "Exists",
      "Message",
      "Description",
      "Action Link",
    ];

    const rows = filteredHealthItems.map((item) => [
      item.label,
      item.key,
      item.category,
      item.status,
      item.count,
      item.exists ? "Yes" : "No",
      item.message,
      item.description,
      item.actionHref,
    ]);

    const csvContent = [headers, ...rows]
      .map((row) =>
        row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")
      )
      .join("\n");

    const blob = new Blob([csvContent], {
      type: "text/csv;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = `pujafresh-system-health-${Date.now()}.csv`;
    link.click();

    URL.revokeObjectURL(url);
    toast.success("System health CSV exported");
  };

  if (isCheckingAuth) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-[#f7f3ea]">
        <div className="rounded-xl bg-white p-6 text-center shadow-sm">
          <h1 className="text-xl font-bold text-gray-900">
            Checking admin access...
          </h1>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#f7f3ea]">
      <Navbar />

      <section className="mx-auto max-w-7xl px-4 py-8">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              System Health
            </h1>

            <p className="mt-1 text-sm text-gray-600">
              Check whether important PujaFresh modules have data and are ready
              for testing, demo and deployment preparation.
            </p>
          </div>

          <div className="flex flex-wrap gap-2">
            <Link
              href="/admin"
              className="rounded border border-[#7a1e13] px-5 py-3 text-sm font-bold text-[#7a1e13] hover:bg-[#7a1e13] hover:text-white"
            >
              Back to Admin
            </Link>

            <Link
              href="/admin/action-center"
              className="rounded border border-[#15803d] px-5 py-3 text-sm font-bold text-[#15803d] hover:bg-[#15803d] hover:text-white"
            >
              Action Center
            </Link>

            <button
              onClick={runHealthCheck}
              className="rounded bg-[#15803d] px-5 py-3 text-sm font-bold text-white hover:bg-[#166534]"
            >
              Run Check
            </button>

            <button
              onClick={exportCsv}
              className="rounded bg-[#f97316] px-5 py-3 text-sm font-bold text-white hover:bg-[#ea580c]"
            >
              Export CSV
            </button>
          </div>
        </div>

        <div className="mt-6 grid gap-4 md:grid-cols-3 lg:grid-cols-7">
          <div className="rounded-xl bg-white p-5 shadow-sm lg:col-span-2">
            <p className="text-sm font-semibold text-gray-500">Health Score</p>
            <h2 className="mt-2 text-4xl font-black text-[#7a1e13]">
              {stats.score}%
            </h2>
          </div>

          <div className="rounded-xl bg-white p-5 shadow-sm">
            <p className="text-sm font-semibold text-gray-500">Healthy</p>
            <h2 className="mt-2 text-3xl font-bold text-green-700">
              {stats.healthy}
            </h2>
          </div>

          <div className="rounded-xl bg-white p-5 shadow-sm">
            <p className="text-sm font-semibold text-gray-500">Warning</p>
            <h2 className="mt-2 text-3xl font-bold text-orange-600">
              {stats.warning}
            </h2>
          </div>

          <div className="rounded-xl bg-white p-5 shadow-sm">
            <p className="text-sm font-semibold text-gray-500">Critical</p>
            <h2 className="mt-2 text-3xl font-bold text-red-600">
              {stats.critical}
            </h2>
          </div>

          <div className="rounded-xl bg-white p-5 shadow-sm">
            <p className="text-sm font-semibold text-gray-500">Modules</p>
            <h2 className="mt-2 text-3xl font-bold text-blue-700">
              {stats.modulesWithData}/{stats.total}
            </h2>
          </div>

          <div className="rounded-xl bg-white p-5 shadow-sm">
            <p className="text-sm font-semibold text-gray-500">Records</p>
            <h2 className="mt-2 text-3xl font-bold text-purple-700">
              {stats.records}
            </h2>
          </div>
        </div>

        {stats.critical > 0 && (
          <div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-5">
            <h2 className="text-xl font-black text-red-700">
              Critical setup items found
            </h2>

            <p className="mt-2 text-sm leading-6 text-red-700">
              Fix critical items before a final demo. Required modules like
              products, store settings, delivery areas, slots and partners should
              be available.
            </p>
          </div>
        )}

        <div className="mt-6 rounded-xl bg-white p-5 shadow-sm">
          <div className="grid gap-4 xl:grid-cols-[1fr_220px_180px_130px]">
            <div>
              <label className="text-sm font-bold text-gray-700">
                Search Modules
              </label>

              <input
                value={searchQuery}
                onChange={(event) => setSearchQuery(event.target.value)}
                placeholder="Search module, key, category or status..."
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2 text-sm outline-none focus:border-[#7a1e13]"
              />
            </div>

            <div>
              <label className="text-sm font-bold text-gray-700">
                Category
              </label>

              <select
                value={categoryFilter}
                onChange={(event) => setCategoryFilter(event.target.value)}
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2 text-sm outline-none focus:border-[#7a1e13]"
              >
                {categoryFilters.map((category) => (
                  <option key={category}>{category}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="text-sm font-bold text-gray-700">Status</label>

              <select
                value={statusFilter}
                onChange={(event) => setStatusFilter(event.target.value)}
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2 text-sm outline-none focus:border-[#7a1e13]"
              >
                {statusFilters.map((status) => (
                  <option key={status}>{status}</option>
                ))}
              </select>
            </div>

            <div className="flex items-end">
              <button
                onClick={clearFilters}
                className="w-full rounded border border-[#7a1e13] px-4 py-2 text-sm font-bold text-[#7a1e13] hover:bg-[#7a1e13] hover:text-white"
              >
                Clear
              </button>
            </div>
          </div>

          <p className="mt-4 text-sm font-semibold text-gray-600">
            Showing {filteredHealthItems.length} of {healthItems.length} module
            {healthItems.length !== 1 ? "s" : ""}.
          </p>
        </div>

        <div className="mt-6 rounded-xl bg-white p-5 shadow-sm">
          <div className="grid gap-4">
            {filteredHealthItems.map((item) => (
              <div
                key={item.key}
                className={`rounded-xl border p-4 ${
                  item.status === "Critical"
                    ? "border-red-200 bg-red-50/40"
                    : item.status === "Warning"
                    ? "border-orange-200 bg-orange-50/30"
                    : "border-gray-200 bg-white"
                }`}
              >
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div className="max-w-4xl">
                    <div className="flex flex-wrap gap-2">
                      <span
                        className={`rounded-full px-3 py-1 text-xs font-bold ${getStatusBadgeClass(
                          item.status
                        )}`}
                      >
                        {item.status}
                      </span>

                      <span
                        className={`rounded-full px-3 py-1 text-xs font-bold ${getCategoryBadgeClass(
                          item.category
                        )}`}
                      >
                        {item.category}
                      </span>

                      <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold text-gray-700">
                        {item.count} record{item.count !== 1 ? "s" : ""}
                      </span>
                    </div>

                    <h3 className="mt-3 text-lg font-black text-gray-900">
                      {item.label}
                    </h3>

                    <p className="mt-2 text-sm leading-6 text-gray-700">
                      {item.description}
                    </p>

                    <p className="mt-2 text-sm font-bold text-gray-800">
                      {item.message}
                    </p>

                    <p className="mt-2 text-xs font-semibold text-gray-500">
                      Storage key: {item.key}
                    </p>
                  </div>

                  <Link
                    href={item.actionHref}
                    className="rounded bg-[#7a1e13] px-5 py-3 text-sm font-bold text-white hover:bg-[#64180f]"
                  >
                    {item.actionLabel}
                  </Link>
                </div>
              </div>
            ))}

            {filteredHealthItems.length === 0 && (
              <div className="py-12 text-center">
                <h2 className="text-xl font-bold text-gray-900">
                  No modules found
                </h2>

                <p className="mt-2 text-gray-600">
                  Try changing search or filters.
                </p>
              </div>
            )}
          </div>
        </div>
      </section>
    </main>
  );
}
